name: 'Liblab SDK updates'
description:
  'Github Action that builds SDKs and publishes PRs using latest Liblab versions'
author: 'Liblab'

branding:
  icon: 'git-pull-request'
  color: 'black'

inputs:
  liblab_token:
    description: 'The Liblab authentication token provided by Liblab CLI'
    required: true
  github_token:
    description: 'The github token that will allow posting PRs to SDK repos'
    required: true

outputs:
  status:
    description: 'Status of the build'

runs:
  using: node20
  main: dist/index.js
